---
# tasks file for nginx

- block: ####RedHat####
  - name: 1.Установка Nginx
    yum: name=nginx state=latest
  when: ansible_os_family == "RedHat"

- block: ####Debian####
  - name: 1.Установка Nginx"
    apt: name=nginx state=latest
  when: ansible_os_family == "Debian"

- name: 2.Перенос конфигурации
  copy: src={{ item }} dest={{ nginxConf }} mode=0644
  with_items:
    - nginx.conf
    - fastcgi.conf
  notify:
  - nginx-reload

- name: 3.Перенос vhost
  copy: src=default.conf dest={{ nginxConf }}/conf.d mode=0644
  notify:
  - nginx-reload

- name: 4.Создание директории для ключей
  file: path={{ nginxConf }}/ssl state=directory

- name: 5.Перенос ssl-ключей
  copy: src=ssl/{{ item }} dest={{ nginxConf }}/ssl/
  with_items:
    - nginx.crt
    - nginx.key

- name: 6.Запуск Nginx
  service: name=nginx state=started enabled=yes
