---
# tasks file for nginx

- block: ####RedHat####
  - name: "Установка Nginx"
    yum: name=nginx state=latest
  when: ansible_os_family == "RedHat"

- block: ####Debian####
  - name: "Установка Nginx"
    apt: name=nginx state=latest
  when: ansible_os_family == "Debian"

- name: Перенос конфигурации
  file: src=nginx.conf dest={{ nginxConf }} mode=0644
  notify:
  - nginx-reload

- name: Создание директории для ключей
  file: path={{ nginxConf }}/ssl state=directory

- name: Перенос ssl-ключей
  file: src=ssl/{{ item }} dest={{ nginxConf }}/ssl/
  withitem:
    - nginx.crt
    - nginx.key

- name: Перенос vhost
  file: src=default.conf dest={{ nginxConf }}/conf.d mode=0644
  notify:
  - nginx-reload

- name: Запуск Nginx
  service: name=nginx state=started enabled=yes
