---
# tasks file for php-fpm

- block: #### RedHat ####
  - name: 1.Проверка, установлен ли epel-repo.
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result

  - name: 2.Установка epel-repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    when: not epel_repofile_result.stat.exists

  - name: 3.Добавление EPEL GPG-ключа.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: not epel_repofile_result.stat.exists

  - name: 4.Проверка, установлен ли remi-repo.
    stat: path={{ remi_repofile_path }}
    register: remi_repofile_result

  - name: 5.Установка remi-repo
    yum:
      name: "{{ remi_repo_url }}"
      state: present
    register: result
    when: not remi_repofile_result.stat.exists

  - name: 6.Добавление REMI GPG-ключа.
    rpm_key:
      key: "{{ remi_repo_gpg_key_url }}"
      state: present
    when: not remi_repofile_result.stat.exists

  - name: 7.yum-utils install
    yum: name=yum-utils state=latest

  - name: 8.enable remi-php72
    shell: yum-config-manager --enable remi-php72

  - name: 9.Установка пакетов
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - php72
      - php72-php-fpm
      - php72-php-gd
      - php72-php-json
      - php72-php-mbstring
      - php72-php-mysqlnd
      - php72-php-xml
      - php72-php-xmlrpc
      - php72-php-opcache

  when: ansible_os_family == 'RedHat'

- name: 10. Запуск PHP-FPM
  service: name=php72-php-fpm state=started enabled=yes

- name: 11. Перенос конфигурации
  copy: src=www.conf dest=/etc/opt/remi/php72/php-fpm.d/ mode=0644
  notify: 
    - fpm-reload