---

- name: Установка Apache и загрузка html-страницы
  hosts: node1
  become: yes

  vars:
          src_folder: /home/revolman/ansible/MySite
          dst_folder: /var/www/html

  tasks:
          - name: Дистрибутив
            debug: var=ansible_os_family

          - block:    ##### Block for Redhat #####
                    - name: Установка Apache на RedHat-серверы
                      yum: name=httpd state=latest
                      
                    - name: Запуск Apache RedHat
                      service: name=httpd state=started enabled=yes
            when: ansible_os_family == "RedHat"

          - block:    ##### Block for Debian #####
                    - name: Установка Apache на Debian-серверы
                      apt: name=apache2 state=latest

                    - name: Запуск Apache Debian
                      service: name=apache2 state=started enabled=yes
            when: ansible_os_family == "Debian"

          - name: Копирование html-файлов
            copy: src={{ src_folder }}/{{ item }} dest={{ dst_folder }} mode=0555

          # copy: src={{ item }} dest={{ dst_folder }} mode=0555
          # with_fileglob: "{{ src_folder }}/*.*"


            loop:
                    - "index.html"
                    - "base.html"
            
            notify: 
                    - redhat apache reload
                    - debian apache reload

  handlers:
          - name: redhat apache reload
            service: name=httpd state=reloaded
            when: ansible_os_family == "RedHat"

          - name: debian apache reload
            service: name=apache2 state=reloaded
            when: ansible_os_family == "Debian"

...
