---

- name: install python
  hosts: k8s
  become: yes

  tasks:

  - block:
  
      - name: Установка Python
        apt:
          name: python
          state: latest

    when: ansible_os_family == "Debian"
  
...