---
# tasks file for wordpress

- name: Закачка архива wordpress
  get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz mode=0755

- name: Распаковка
  unarchive: 
    remote_src: yes
    src: /tmp/wordpress.tar.gz
    dest: /usr/share/nginx/
    owner: nginx
    group: nginx
