---
<<<<<<< Updated upstream
# Основной файл

# Установка дял RedHat
- include_tasks: redhat-install.yml
  when: ansible_os_family == 'RedHat'

# Конфигурирование mysql 
- include_tasks: configure.yml
 
=======
# tasks file for mariadb

- block:
  - name: 
>>>>>>> Stashed changes
