---
# Основной файл

# Определение переменных
- include_tasks: variables.yml

# Установка для RedHat
- include_tasks: redhat-install.yml
  when: ansible_os_family == 'RedHat'

# Проверка, установиливались ли пакеты
- name: Проверка, установиливались ли пакеты
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed) }}"

# Конфигурирование mysql 
- include_tasks: configure.yml
- include_tasks: secure-installation.yml
- include_tasks: databases.yml
- include_tasks: users.yml