---
# Основной файл

# Установка дял RedHat
- include_tasks: redhat-install.yml
  when: ansible_os_family == 'RedHat'

# Конфигурирование mysql 
- include_tasks: variables.yml
- include_tasks: configure.yml