---

- name: Установка Apache и загрузка html-страницы
  hosts: node1
  become: yes

  vars:
          src_file: ./MySite/index.html
          dst_file: /var/www/html

  tasks:
          - name: Дистрибутив
            debug: var=ansible_os_family

          - block:    ##### Block for Redhat #####
                    - name: Установка Apache на RedHat-серверы
                      yum: name=httpd state=latest
                      
                    - name: Копирование html-страницы
                      copy: src={{ src_file }} dest={{ dst_file }} mode=0555
                      notify: redhat apache reload

                    - name: Запуск Apache RedHat
                      service: name=httpd state=started enabled=yes

            when: ansible_os_family == "RedHat"

          - block:    ##### Block for Debian #####
                    - name: Установка Apache на Debian-серверы
                      apt: name=apache2 state=latest

                    - name: Копирование html-страницы
                      copy: src={{ src_file }} dest={{ dst_file }} mode=0555
                      notify: debian apache reload

                    - name: Запуск Apache Debian
                      service: name=apache2 state=started enabled=yes

            when: ansible_os_family == "Debian"


  handlers:
          - name: redhat apache reload
            service: name=httpd state=reloaded

          - name: debian apache reload
            service: name=apache2 state=reloaded

...
