---

- name: Сохранение вывода при помоши Register 
  hosts: all
  become: yes

  tasks:
          - name: Сохранение вывода в переменную results
            shell: uptime
            register: results

          - name: Вывод переменной results
            debug:
                    var: results.stdout

...
